    package sintactico;

    import java_cup.runtime.Symbol;

    parser code {: /* Retorno del símbolo que se está realizando */
        private Symbol s;

        public void syntax_error(Symbol s){
            this.s = s;}

        public Symbol getS(){
            return this.s;}
    :};

    terminal CREATE, DATABASE, NOMBRE, PUNTOCOMA;

    non terminal SENTENCIA;

    start with SENTENCIA;

    SENTENCIA ::= CREATE DATABASE NOMBRE PUNTOCOMA;

