
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Mar 21 11:43:28 CST 2023
//----------------------------------------------------

package sintactico;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CREATE = 2;
  public static final int error = 1;
  public static final int DATABASE = 3;
  public static final int NOMBRE = 4;
  public static final int PUNTOCOMA = 5;
  public static final int EOF = 0;
}

